name: test
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: test build
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: test build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
            
